export const TOGGLE_NOTE_INFO = 'TOGGLE_NOTE_INFO';
export const MOVE_TO_TRASH_REQUEST = 'MOVE_TO_TRASH_REQUEST';
export const MOVE_TO_TRASH_SUCCEEDED = 'MOVE_TO_TRASH_SUCCEEDED';
export const MOVE_TO_TRASH_FAILURE = 'MOVE_TO_TRASH_FAILURE';
export const TOGGLE_SIDEBAR_VISIBILITY = 'TOGGLE_SIDEBAR_VISIBILITY';
