export const NOTE_SAVE_REQUEST = 'NOTE_SAVE_REQUEST';
export const NOTE_SAVE_SUCCEEDED = 'NOTE_SAVE_SUCCEEDED';
export const NOTE_SAVE_FAILURE = 'NOTE_SAVE_FAILURE';
export const NOTE_EDIT = 'NOTE_EDIT';
