@host = localhost:4000
@accessToken = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2JhZTgyYzcwZDg2ZDEwNGNiNjA1ZGYiLCJpYXQiOjE1NTU3NTQ3MjYsImV4cCI6MTU1NTc1ODMyNn0.9Uc4ym3MkxmWUrRycyl6xU3J-zy1wbzUbWdfYiOE9d6zB877owfIhZW8TpdPbwV7URvccivgmdHbm0OzwPDfNg

###
GET http://{{host}}/notes
Accept: application/json
Authorization: {{accessToken}}

###
POST http://{{host}}/notes
Accept: application/json
Content-Type: application/json
Authorization: {{accessToken}}

{
  "text": "Lorem Ipsum"
}

###
PATCH http://{{host}}/notes/5cbae8e170d86d104cb605e2
Accept: application/json
Content-Type: application/json
Authorization: {{accessToken}}

{
  "text": "Lorem Ipsum"
}

###
DELETE http://{{host}}/notes
Accept: application/json
Authorization: {{accessToken}}

###
PATCH  http://{{host}}/notes/5cbae8e170d86d104cb605e2/tag/5cbae8a070d86d104cb605e1
Accept: application/json
Authorization: {{accessToken}}

###
PATCH  http://{{host}}/notes/5cbae8e170d86d104cb605e2/untag/5cbae8a070d86d104cb605e1
Accept: application/json
Authorization: {{accessToken}}
