@host = localhost:4000
@accessToken = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2JhZTk0YjcwZDg2ZDEwNGNiNjA1ZTQiLCJpYXQiOjE1NTU3NTMzMjIsImV4cCI6MTU1NTc1NjkyMn0.NVPqKrCKzq_WUI3L11Boy61MxHOrpUjdUgfHPhGpMAzfMsuNxhoeTzaiCWgVs6-iX3_5KYSkRbz0Pllv8Hy-rA

###
GET http://{{host}}/tags
Accept: application/json
Authorization: {{accessToken}}

###
POST http://{{host}}/tags
Accept: application/json
Content-Type: application/json
Authorization: {{accessToken}}

{
  "name": "Test Tag"
}

###
DELETE http://{{host}}/tags/5cbae8a070d86d104cb605e1
Accept: application/json
Authorization: {{accessToken}}
