@host = localhost:4000
@accessToken = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2I2MDgxOTA5N2EyYzFmZWMwZDE0MzciLCJpYXQiOjE1NTU2OTE0MTIsImV4cCI6MTU1NTc3NzgxMn0.NST-7BzsVNrH2kKl4WWWN8kGt7QM3mbl85qbKbkcSLLvM7Xim1oFPdlclVwj-cJNrMaRUAY0OWbcttCCy8eJfw
@refreshToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2I2MDgxOTA5N2EyYzFmZWMwZDE0MzciLCJpYXQiOjE1NTU2OTE0MTIsImV4cCI6MTU1NTY5NTAxMn0.30s1vGsEkWdjdV6czeEVpgSWt1OkC_U_MC5TY-H6UZqyO6tOBXj1-hnH95kvB0mWZpMjnkGCjWsA0A97Arlfbg

POST http://{{host}}/users
Content-Type: application/x-www-form-urlencoded

email=alexander.varivoda.s@gmail.com&displayName=idvar&password=114afb2

###
POST http://{{host}}/register/b5d55396-e205-4f98-aff8-65b4643d8977

###
GET http://{{host}}/users
Accept: application/json
Authorization: {{accessToken}}

###
PATCH http://{{host}}/users
Accept: application/json
Authorization: {{accessToken}}
Content-Type: application/x-www-form-urlencoded

email=alexander.varivoda.s@gmail.com

###
POST http://{{host}}/users/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

email=alexander.varivoda.s@gmail.com&password=114afb2

###
POST http://{{host}}/refresh-token
Accept: application/json
Content-Type: application/json

{"refreshToken": "{{refreshToken}}"}
