@host = localhost:4000
@accessToken = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2JhZTk0YjcwZDg2ZDEwNGNiNjA1ZTQiLCJpYXQiOjE1NTU3NTMzMjIsImV4cCI6MTU1NTc1NjkyMn0.NVPqKrCKzq_WUI3L11Boy61MxHOrpUjdUgfHPhGpMAzfMsuNxhoeTzaiCWgVs6-iX3_5KYSkRbz0Pllv8Hy-rA
@refreshToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2JhZTk0YjcwZDg2ZDEwNGNiNjA1ZTQiLCJpYXQiOjE1NTU3NTMzMjIsImV4cCI6MTU1NTgzOTcyMn0.q2epM-LbN8B0kv369xficlcTzh6JV_MVsxY2rVG5aYXGxTgZOxvnal5DcnfhH9fZ5YPs0jK85JPKL3mahn39mQ

POST http://{{host}}/users
Content-Type: application/x-www-form-urlencoded

email=cukaduvon@max-mail.info&displayName=test&password=114afb2

###
POST http://{{host}}/register/c8ce3f6a-f483-482a-b375-2a1c0ee72562

###
GET http://{{host}}/users
Accept: application/json
Authorization: {{accessToken}}

###
PATCH http://{{host}}/users
Accept: application/json
Authorization: {{accessToken}}
Content-Type: application/x-www-form-urlencoded

email=alexander.varivoda.s@gmail.com

###
POST http://{{host}}/users/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

email=fetudevux@smartbusiness.me&password=114afb2

###
POST http://{{host}}/refresh-token
Accept: application/json
Content-Type: application/json

{"refreshToken": "{{refreshToken}}"}

###
DELETE http://{{host}}/users
Accept: application/json
Authorization: {{accessToken}}
