export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCEEDED = 'FETCH_DATA_SUCCEEDED';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST';
export const ADD_NOTE_SUCCEEDED = 'ADD_NOTE_SUCCEEDED';
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE';
