export const EMAIL_VERIFICATION_SUCCEEDED = 'EMAIL_VERIFICATION_SUCCEEDED';
export const EMAIL_VERIFICATION_FAILURE = 'EMAIL_VERIFICATION_FAILURE';
export const EMAIL_VERIFICATION_REQUEST = 'EMAIL_VERIFICATION_REQUEST';
