export const REDIRECT = 'REDIRECT';
export const USER_REQUEST_SUCCEEDED = 'USER_REQUEST_SUCCEEDED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const UPDATE_EMAIL_SUCCEEDED = 'UPDATE_EMAIL_SUCCEEDED';
